class functions
{
    file = "klpq\mydac\functions";

    class preInit {preInit = 1;};
    class postInit {postInit = 1;};
    class createUnit {};
    class createGroup {};
    class createCrew {};
    class applySkill {};
    class applySkillType {};
    class getSkill {};
    class createVehicle {};
    class getSide {};
    class createZone {};
    class createCamp {};
    class generateWaypoints {};
    class generatePatrol {};
    class reduceGroup {};
    class buildGroup {};
    class dynamicLoop {};
    class disableZone {};
    class enableZone {};
    class debugHint {};
    class disableCamp {};
    class enableCamp {};
    class campLoop {};
    class zoneCreateInfGroup {};
    class zoneCreateInfGroups {};
    class zoneCreateWhlGroup {};
    class zoneCreateWhlGroups {};
    class zoneCreateTrcGroup {};
    class zoneCreateTrcGroups {};
    class zoneCreateAirGroup {};
    class zoneCreateAirGroups {};
    class zoneCreateNvlGroup {};
    class zoneCreateNvlGroups {};
    class zoneAddInf {};
    class zoneAddWhl {};
    class zoneAddTrc {};
    class zoneAddAir {};
    class zoneAddNvl {};
    class campAddInf {};
    class campAddWhl {};
    class campAddTrc {};
    class campAddAir {};
    class campAddNvl {};
    class garbageCollectionLoop {};
};
